### ISSUE TITLE
双面打印模式下空页不当

### ISSUE THREAD

**Issue by CCXXXI** [Koyamin/ECNUThesis-Undergraduate#14]
![e541dd7af9314e05dbb26bb88281119](https://github.com/Koyamin/ECNUThesis-Undergraduate/assets/25550534/b21dda66-0a02-4ad6-b0dc-1053b5972b91)

- 在指定 `declarePageResource` 为 PDF 文件时，论文诚信承诺和目录之间缺少空页

**Comment by Koyamin** [comment]
该功能旨在生成电子存档板论文时使用。个人不建议在打印模式使用
