### ISSUE TITLE
TeX Live 2023 排版异常

### ISSUE THREAD

**Issue by CCXXXI** [Koyamin/ECNUThesis-Undergraduate#3]
![image](https://user-images.githubusercontent.com/25550534/228446142-2fd51a43-10b9-470b-80a1-b32c2235f73a.png)

~~不太确定是不是 TeX Live 2023 的新问题，但是看仓库自带的两周前的示例是正常的，可疑的只有 TeX Live 版本了。~~

已确认，见后续补充。

**Comment by CCXXXI** [comment]
该问题可以在 GitHub Actions 环境下复现：
https://github.com/CCXXXI/thesis/actions/runs/4571401362

可能的相关错误消息：
https://github.com/CCXXXI/thesis/actions/runs/4571401362/jobs/8069659642#step:4:535
```
./main.tex:114: You can't use `macro parameter character #' in restricted horiz
ontal mode.
<argument> ...map_inline:xn {\l__ecnu_tmpa_tl }{##
                                                  1\hfil }\unskip 
l.114 \begin{document}
```

加了 `-f` 强制生成的最终结果：
https://github.com/CCXXXI/thesis/suites/11934426081/artifacts/625338886

**Comment by CCXXXI** [comment]
旧版本测试结果如下：

- `@20230301`: [bad](https://github.com/CCXXXI/thesis/actions/runs/4571474522)
- `@20230201`: [bad](https://github.com/CCXXXI/thesis/actions/runs/4571498843)
- `@20230101`: [bad](https://github.com/CCXXXI/thesis/actions/runs/4571530802)
- `@20221001`: [bad](https://github.com/CCXXXI/thesis/actions/runs/4571553924)
- `@20220808`: [bad](https://github.com/CCXXXI/thesis/actions/runs/4571673482)
- `@20220801`: [good](https://github.com/CCXXXI/thesis/actions/runs/4571710553)
- `@20220701`: [good](https://github.com/CCXXXI/thesis/actions/runs/4571616132)
- `@20220301`: [good](https://github.com/CCXXXI/thesis/actions/runs/4571581285)

**Comment by qcmiao1998** [comment]
https://github.com/Koyamin/ECNUThesis-Undergraduate/blob/3fcb918a77d22856ef01684a45dc9c988d1f014f/ecnuthesis.cls#L763-L764
与当前版本不兼容，似乎原因在于 `\tl_map_inline:xn` 未找到定义，我不知道使用该函数具体目的何在，请问一下作者 @Koyamin

将其修改为
```
\hbox_to_wd:nn {#1} {\unskip #2 \unskip}
```
可使显示正常

**Comment by CCXXXI** [comment]
为什么旧版没这个问题？（不重要，纯好奇

**Comment by qcmiao1998** [comment]
> 为什么旧版没这个问题？（不重要，纯好奇

可能要去翻一下 latex3 的提交记录了

**Comment by Koyamin** [comment]
最近也在用模版写论文，暂时还不方便用Tex Live 2023测试，抱歉。

https://github.com/Koyamin/ECNUThesis-Undergraduate/blob/3fcb918a77d22856ef01684a45dc9c988d1f014f/ecnuthesis.cls#L763-L764

`\tl_map_inline:xn {<token list>} {<inline function>}`的作用是对的token list中的每个元素，都应用inline  function。看到最后编译结果出现了“1”，应该是`##`没有被正确转义。我猜原因是在该函数的参数`xn`上，不妨试试改成`nn`？

另外，无意中发现 `\hbox_to_wd:nn` 其实是可以直接使用的，仅需改成
```latex
\hbox_to_wd:nn {#1} {#2}
```
即可达到所需要的效果

**Comment by Koyamin** [comment]
87eabf7
应该是没问题了。
